"use client";

import { useQuery } from "@tanstack/react-query";
import { usePublicClient } from "wagmi";
import { decodeEventLog, type Address, type PublicClient } from "viem";
import { GARANTYA_ABI, FACTORY_DEPLOY_BLOCK } from "@/lib/contract";
import { logger } from "@/lib/logger";

export interface TimelineEvent {
  id: string;
  label: string;
  detail?: string;
  timestamp?: number;
  color: "green" | "amber" | "red" | "blue" | "stone";
  eventName: string;
  eventArgs?: Record<string, unknown>;
}

type Args = Record<string, unknown>;

// Only colors here — labels are generated by EventTimeline with i18n
const EVENT_COLORS: Record<string, TimelineEvent["color"]> = {
  ContractCreated:           "stone",
  Funded:                    "green",
  Proposed:                  "amber",
  Accepted:                  "green",
  Rejected:                  "red",
  Resolved:                  "blue",
  TimeoutExecuted:           "stone",
  ArbitratorTimeoutExecuted: "amber",
  Reclaimed:                 "stone",
  Cancelled:                 "stone",
  CancelledPending:          "stone",
  Withdrawn:                 "green",
};

async function fetchEvents(client: PublicClient, address: Address): Promise<TimelineEvent[]> {
  logger.log("[Garantya:useContractEvents] Fetching logs para", address);

  // Get current block once to estimate timestamps from block numbers
  const [logs, latestBlock] = await Promise.all([
    client.getLogs({ address, fromBlock: FACTORY_DEPLOY_BLOCK, toBlock: "latest" }),
    client.getBlock({ blockTag: "latest" }),
  ]);
  logger.log("[Garantya:useContractEvents] Logs crudos recibidos:", logs.length);

  // Fuji produces ~1 block/sec — estimate timestamp from block number offset
  const nowTs      = Number(latestBlock.timestamp);
  const nowBlock   = Number(latestBlock.number);

  const parsed: TimelineEvent[] = [];
  for (const log of logs) {
    try {
      const decoded = decodeEventLog({
        abi: GARANTYA_ABI,
        data: log.data,
        topics: log.topics,
      });
      const eventName = String(decoded.eventName);
      const color = EVENT_COLORS[eventName];
      if (!color) continue;
      const blockDiff = log.blockNumber ? nowBlock - Number(log.blockNumber) : 0;
      const timestamp = nowTs - blockDiff; // ~1 block/sec on Fuji
      parsed.push({
        id: `${log.transactionHash}-${log.logIndex ?? 0}`,
        label: eventName,
        color,
        eventName,
        eventArgs: decoded.args as Args,
        timestamp,
      });
    } catch {}
  }
  logger.log("[Garantya:useContractEvents] Eventos parseados:", parsed.map(e => e.eventName));
  return parsed;
}

export function useContractEvents(address: Address) {
  const client = usePublicClient();

  const { data: events = [], isLoading } = useQuery({
    queryKey: ["contractEvents", address],
    queryFn: () => fetchEvents(client!, address),
    enabled: !!client,
    staleTime: 60_000,      // 1 min — events only change on new txs
    gcTime:    10 * 60_000, // 10 min — past events never change
  });

  return { events, isLoading };
}
