"use client";

import { useQuery } from "@tanstack/react-query";
import { usePublicClient } from "wagmi";
import { decodeEventLog, type Address, type PublicClient } from "viem";
import { GARANTYA_ABI, FACTORY_DEPLOY_BLOCK } from "@/lib/contract";
import { logger } from "@/lib/logger";

export interface TimelineEvent {
  id: string;
  label: string;
  detail?: string;
  timestamp?: number;
  color: "green" | "amber" | "red" | "blue" | "stone";
  eventName: string;
  eventArgs?: Record<string, unknown>;
}

type Args = Record<string, unknown>;

// Only colors here — labels are generated by EventTimeline with i18n
const EVENT_COLORS: Record<string, TimelineEvent["color"]> = {
  ContractCreated:           "stone",
  Funded:                    "green",
  Proposed:                  "amber",
  Accepted:                  "green",
  Rejected:                  "red",
  Resolved:                  "blue",
  TimeoutExecuted:           "stone",
  ArbitratorTimeoutExecuted: "amber",
  Reclaimed:                 "stone",
  Cancelled:                 "stone",
  CancelledPending:          "stone",
  Withdrawn:                 "green",
};

async function fetchEvents(client: PublicClient, address: Address): Promise<TimelineEvent[]> {
  logger.log("[Garantya:useContractEvents] Fetching logs para", address);
  const logs = await client.getLogs({
    address,
    fromBlock: FACTORY_DEPLOY_BLOCK,
    toBlock: "latest",
  });
  logger.log("[Garantya:useContractEvents] Logs crudos recibidos:", logs.length);

  // Fetch block timestamps in parallel (deduplicated by block number)
  const uniqueBlocks = [
    ...new Set(logs.map(l => l.blockNumber).filter((bn): bn is bigint => bn != null)),
  ];
  const timestamps = new Map<bigint, number>();
  await Promise.all(
    uniqueBlocks.map(async (bn) => {
      try {
        const block = await client.getBlock({ blockNumber: bn });
        timestamps.set(bn, Number(block.timestamp));
      } catch {}
    })
  );

  const parsed: TimelineEvent[] = [];
  for (const log of logs) {
    try {
      const decoded = decodeEventLog({
        abi: GARANTYA_ABI,
        data: log.data,
        topics: log.topics,
      });
      const eventName = String(decoded.eventName);
      const color = EVENT_COLORS[eventName];
      if (!color) continue;
      parsed.push({
        id: `${log.transactionHash}-${log.logIndex ?? 0}`,
        label: eventName, // fallback; EventTimeline overrides with i18n
        color,
        eventName,
        eventArgs: decoded.args as Args,
        timestamp: log.blockNumber ? timestamps.get(log.blockNumber) : undefined,
      });
    } catch {}
  }
  logger.log("[Garantya:useContractEvents] Eventos parseados:", parsed.map(e => e.eventName));
  return parsed;
}

export function useContractEvents(address: Address) {
  const client = usePublicClient();

  const { data: events = [], isLoading } = useQuery({
    queryKey: ["contractEvents", address],
    queryFn: () => fetchEvents(client!, address),
    enabled: !!client,
    staleTime: 30_000,   // 30s — blockchain data changes only on new txs
    gcTime:    5 * 60_000, // 5 min in cache after unmount
  });

  return { events, isLoading };
}
